config/routes.rb
Rails.application.routes.draw do

  # get 'recipe_comments/index'
  #
  # get 'recipes/index'

  devise_for :users

  root to: "welcome#index"
  
  resources :posts do
    resources :comments
  end
    resources :recipes do
      resources :recipe_comments
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  default_scope { order('updated_at DESC') } # sorts by updated at in reverse orderr
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  default_scope { order('updated_at DESC') } # sorts by updated at in reverse orderr
  has_many :comments
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  default_scope { order('updated_at DESC') } # sorts by updated at in reverse orderr
  has_many :recipe_comments
  belongs_to :user
end

app/models/recipe_comment.rb
class RecipeComment < ApplicationRecord

  default_scope { order('updated_at DESC') } # sorts by updated at in reverse orderr
  belongs_to :recipe
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :recipes
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def new
    @post = Post.new
  end
  def create
    @post = Post.create!(post_params)
    redirect_to post_path(@post)
  end
  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end
  #post params are the things the post HAS, that we can access.
  private
  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/recipe_comments_controller.rb
class RecipeCommentsController < ApplicationController
  before_action :set_recipe_comment, only: [:show, :edit, :update, :destroy]
  def show
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_comment = Recipe.find(params[:id])
  end
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_comment = RecipeComment.new
  end
  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_comment = @recipe.recipe_comments.create(comment_params)
    redirect_to recipe_path(@recipe)
  end
  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
  private
  def comment_params
    params.require(:comment).permit(:body)
  end
    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_comment_params
      params.require(:recipe_comment).permit(:title, :body)
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
def index
  @recipes = Recipe.all
end
def show
  @recipe = Recipe.find(params[:id])
end
def edit
  @post = Post.find(params[:id])
end
def new
  @post = Post.new
end
def create
  @post = Post.create!(post_params)
  redirect_to post_path(@post)
end
def update
  @post = Post.find(params[:id])
  @post.update(post_params)
  redirect_to post_path(@post)
end
def destroy
  @post = Post.find(params[:id])
  @post.destroy
  redirect_to posts_path
end
#post params are the things the post HAS, that we can access.
private
def post_params
  params.require(:recipe).permit(:name, :body, :glass)
end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_comments_helper.rb
module RecipeCommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit %>
<% end %>

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= render "form" %>

app/views/comments/new.html.erb
<h2>New Comment</h2>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Drink Recipes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/css?family=Bitter|Roboto+Condensed" rel="stylesheet">
</head>
<body>
  <ul class="slideshow">
     <li>
       <span>Image 01</span>
     </li>
     <li>
       <span>Image 02</span>
     </li>
     <li>
       <span>Image 03</span>
     </li>
     <li>
       <span>Image 04</span>
     </li>
   </ul>
<h1 class='drink'><%= link_to "Drink Recipe", root_path %></h1>
<div class='sign'>
  <% if !current_user %>
  <div class='users'>
<%= link_to "Sign up", new_user_registration_path %>
<%= link_to "Sign in", new_user_session_path %>
  <% else %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
<% end %>
</div>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>


</body>
</html>

app/views/posts/_form.html.erb
<!--The standard form but I added glass so you can change/update/create a glass  -->

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :Post_Content %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Drink</h2>
<%= render "form" %>

app/views/posts/index.html.erb
<!-- So it's literally the basic form. What is being displayed. -->
<%= link_to "Create New Post!", new_post_path %>
<section>
  <% @posts.each do |post| %>
    <article>
      <h2><%= link_to post.title, post_path(post) %></h2>
      <time>Updated <%= post.updated_at %></time>
      <p><%= post.body %></p>

    </article>
  <% end %>
</section>

app/views/posts/new.html.erb
<!-- Wanna make a new drink? Call up the form, where there's the name, ingreds and glass -->

<h2>New Post! What's troubling you, questions, comments, etc.  Start a discussion</h2>

<%= render "form" %>

app/views/posts/show.html.erb
<%= link_to "&larr; Back".html_safe, posts_path %>
<article>
  <h2><%= @post.title %></h2>
  <time>Updated <%= @post.updated_at %></time>
  <p><%= @post.body %></p>
  
  <%= link_to "Edit Post", edit_post_path(@post) %>
  <%= link_to "Delete Post", post_path(@post), method: :delete %>
  <div class='comments'>
  <h3>Comments</h3>
  <%= link_to "Add new comment", new_post_comment_path(@post) %>
  <% @post.comments.each do |comment| %>
    <div>
      <time>Updated <%= comment.updated_at %></time>
      <p>
	<%= comment.body %>
      </p>
      <%= link_to "Edit", edit_post_comment_path(@post, comment) %> |
      <%= link_to "Delete", post_comment_path(@post, comment), method: :delete %>
    </div>
  <% end %>
  </div>
</article>

app/views/recipe_comments/_form.html.erb
<%= form_for(recipe_comment) do |f| %>
  <% if recipe_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe_comment.errors.count, "error") %> prohibited this recipe_comment from being saved:</h2>

      <ul>
      <% recipe_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_comments/edit.html.erb
<h1>Editing Recipe Comment</h1>

<%= render 'form', recipe_comment: @recipe_comment %>

<%= link_to 'Show', @recipe_comment %> |
<%= link_to 'Back', recipe_comments_path %>

app/views/recipe_comments/new.html.erb
<h1>New Recipe Comment</h1>

<%= render 'form', recipe_comment: @recipe_comment %>

<%= link_to 'Back', recipe_comments_path %>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="field">
    <%= f.label :glass %>
    <%= f.text_field :glass %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Show', @recipe %> |
<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class='RecipesTop'>Recipes</h1>
<link rel="stylesheet" href="../../stylesheets/recipes.scss">

<table>
  <!-- <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Glass</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @recipes.each do |recipe| %>
    <article>
      <h2><%= link_to recipe.name, recipe_path(recipe) %></h2>
      <time>Updated <%= recipe.updated_at %></time>
      <p><%= recipe.body %></p>
      <p>Served in: <%= recipe.glass %></p>
  --------------------------------------------------------------------
    </article>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<%= link_to "&larr; Back".html_safe, recipes_path %>
<article>
  <h2><%= @recipe.name %></h2>
  <time>Updated <%= @recipe.updated_at %></time>
  <p><%= @recipe.body %></p>
  <p>Served in: <%= @recipe.glass %></p>
  <%= link_to "Edit Drink", edit_recipe_path(@recipe) %>
  <%= link_to "Delete Drink", recipe_path(@recipe), method: :delete %>

</article>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Broken Bottles</title>
    <h1>Welcome to Broken Bottles</h1>
  </head>
  <body>
    <div class='links'>
    <%= link_to "Posts", posts_path%>
    <div class='recipeslink'><%= link_to "Recipes", recipes_path%></div>
  </div>
  <p>Broken Bottles is your one-stop resource for drink related questions, comments, and of course recipes.  Add reviews, register as a user, comment on posts, and answer community generated questions!</p>
  <br>
  <a href="http://www.beerawesome.com">Don't forget to check out BeerAwesome for the best in beer reviews</a>
  </body>
</html>